### ISSUE TITLE
You remove the horizontal flip from the geometric transformations. Is there a reason?

### ISSUE THREAD

**Issue by lithostark** [aamir-mustafa/Transformation-CR#1]
Hi, first of all, thank you for sharing the implementation of your work. I'm very interested in it.
I notice that the horizontal flip was removed from the transformations list.

https://github.com/aamir-mustafa/Transformation-CR/blob/31966fc05074ec793f38ed43ba2c853cf1b69c16/train_tcr_vgg_loss.py#L106

I'm wondering if the flip operation degrades the performance? Or it does not improve the performance.
I'm just curious about how much improvement I should expect by adding the flip into the transformations.

**Comment by aamir-mustafa** [comment]
Hi, Thanks for your interest in our paper. Here we have left the option open to uncomment the hflip function for training the model. In our experimentations, we have included  hflip as well.
Its an interesting obersevation. I am not very sure what the difference in the performance with and without hflip. I will look into it.

Best

Aamir
