### ISSUE TITLE
Reproducing the Results

### ISSUE THREAD

**Issue by udithhaputhanthri** [aamir-mustafa/Transformation-CR#3]
Hi,

Thank you for the excellent work.

I ran the scripts that are given in this repository for the super-resolution task. But ([train_tcr.py](https://github.com/aamir-mustafa/Transformation-CR/blob/master/train_tcr.py)) perform worse than the [train.py](https://github.com/aamir-mustafa/Transformation-CR/blob/master/train.py) script. I wonder what would I have missed here?

![tcr](https://user-images.githubusercontent.com/53050875/187095104-ced89150-4b53-43ad-8a93-3ee8729e8b7e.png)
![baseline](https://user-images.githubusercontent.com/53050875/187095105-2b6d1b32-7b73-4bdf-ae85-b72bed6050fb.png)

Thank you

**Comment by aamir-mustafa** [comment]
Hi,

There are a few things that you need to take care of when running the training.
The batch size must be increased. Currently in the repo a batch size of 4 is given. This is for simplicity if someone wants to run the code on less GPU memory. The batch size parameter depends on the img2img translation task you are working on. Just make sure, as per our observations the best performance of TCR is when the batch size factor (r) of the unsupervised data is 10 times that of supervised data.

You may want to warm up the network for best performance, i.e. intialize the training on the supervised data for a few epochs.

Furthermore, I assume that currently you are working on the SISR task. The parameters for transformations may change for different applications.

Hope this helps

**Comment by udithhaputhanthri** [comment]
@aamir-mustafa 

Hi, Thank you for the response. 

I tried warming up the method (trained with supervised data for 500 epochs and then used both supervised and unsupervised data for the training for another 500 epochs. Altogether, 1000 epochs are used). However, I could not observe a significant performance increment from the 500th (**Avg. PSNR: 24.7431 dB**) epoch to 1000th (**Avg. PSNR: 24.7348 dB**) epoch. For the comparison, I have done the same with the baseline model (trained only with 20% supervised data (i.e. weight/ lambda=0.0) for 1000 epochs). After 1000 epochs, the performance was  **Avg. PSNR: 24.7664 dB** which is slightly better.


I wonder what might be the batch size I should use for supervised, and unsupervised data, in order to reproduce the SISR task results in the paper?

Thank you
